In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## Create & Read

#### 1D Array

In [5]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(6,)

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr1.ndim

1

In [10]:
arr1.size

6

### 2D Array

In [12]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 3)

In [15]:
arr2.dtype

dtype('int32')

arr2.size

#### 3D Array

In [18]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])

In [19]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [20]:
arr3.ndim

3

In [21]:
arr3.shape

(3, 2, 3)

In [22]:
arr3.size

18

### Create Random Array

In [43]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.74994681, 0.56879298, 0.1781619 ],
        [0.83344849, 0.1195781 , 0.7152407 ]],

       [[0.87539206, 0.67038243, 0.53704943],
        [0.32829031, 0.47417876, 0.50175701]],

       [[0.7700333 , 0.25398708, 0.94848343],
        [0.91113174, 0.97038811, 0.57915199]]])

In [45]:
randomArr.dtype

dtype('float64')

In [47]:
zeros = np.zeros((3, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
zeros.ndim

3

In [53]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [55]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [67]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [73]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [75]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [81]:
arr3[1][0][1]

5

In [83]:
arr3[1, 0, 1]

5

### Update & Delete

In [87]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [89]:
a1

array([[[0.67652439, 0.50564762],
        [0.92036441, 0.68141418],
        [0.21344874, 0.62002033]],

       [[0.618722  , 0.43008509],
        [0.20186407, 0.92241515],
        [0.40077241, 0.52168803]]])

In [91]:
a2

array([[[0.30768126, 0.93463383],
        [0.62030231, 0.60330773],
        [0.23350757, 0.48207547]],

       [[0.6059796 , 0.57098588],
        [0.52334426, 0.6911646 ],
        [0.56215113, 0.46555412]]])

### Basic Math Operations

In [94]:
np.add(a1, a2)

array([[[0.98420565, 1.44028145],
        [1.54066672, 1.28472191],
        [0.44695631, 1.1020958 ]],

       [[1.2247016 , 1.00107097],
        [0.72520832, 1.61357975],
        [0.96292355, 0.98724214]]])

In [96]:
np.subtract(a1, a2)

array([[[ 0.36884312, -0.42898621],
        [ 0.30006211,  0.07810645],
        [-0.02005883,  0.13794486]],

       [[ 0.01274239, -0.14090079],
        [-0.32148019,  0.23125054],
        [-0.16137872,  0.05613391]]])

In [98]:
np.divide(a1, a2)

array([[[2.19878319, 0.54101147],
        [1.48373528, 1.12946369],
        [0.91409772, 1.28614785]],

       [[1.02102776, 0.75323245],
        [0.38571946, 1.334581  ],
        [0.71292645, 1.12057441]]])

In [100]:
np.multiply(a1, a2)

array([[[0.20815388, 0.47259537],
        [0.57090417, 0.41110244],
        [0.0498419 , 0.29889659]],

       [[0.37493291, 0.24557251],
        [0.1056444 , 0.6375407 ],
        [0.22529467, 0.24287401]]])

### Statistical Operations

In [102]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [105]:
sqrt

5.0

In [107]:
abs

2

In [109]:
power

256

In [111]:
log

3.2188758248682006

In [113]:
mins

0.20186406664966694

In [115]:
maxs

0.934633829854777

### Update

In [118]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [122]:
arr3[0][0][2] = 500

In [124]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [128]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [132]:
arr3.shape

(3, 2, 3)

In [138]:
arr3_reshape = arr3.reshape(2, 3, -1)
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [136]:
arr3_reshape.shape

(2, 3, 3)

#### Appending & Inserting

In [141]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [143]:
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [149]:
appd = np.append(zeros, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [151]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [153]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [157]:
inserted_array = np.insert(zeros, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [160]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.88262314, 0.39621215, 0.37122165],
        [0.22128241, 0.22605594, 0.10137297]],

       [[0.98284213, 0.23696146, 0.80302497],
        [0.20106891, 0.98860942, 0.76052745]],

       [[0.87398306, 0.76966607, 0.84050792],
        [0.46012843, 0.03977637, 0.54781063]]])

In [166]:
arr5 = np.delete(arr4, 0, axis=1)

In [168]:
arr5

array([[[0.22128241, 0.22605594, 0.10137297]],

       [[0.20106891, 0.98860942, 0.76052745]],

       [[0.46012843, 0.03977637, 0.54781063]]])

In [170]:
np.save("new_array", arr5)

In [172]:
np.load("new_array.npy")

array([[[0.22128241, 0.22605594, 0.10137297]],

       [[0.20106891, 0.98860942, 0.76052745]],

       [[0.46012843, 0.03977637, 0.54781063]]])